# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-01 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_type', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number3', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('vehicle_make', models.CharField(max_length=30)),
                ('vehicle_model', models.CharField(max_length=30)),
                ('registration_number', models.CharField(max_length=30)),
                ('YOM', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=30)),
                ('cover_type', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMotor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_type', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('vehicle_make', models.CharField(max_length=30)),
                ('vehicle_model', models.CharField(max_length=30)),
                ('registration_number', models.CharField(max_length=30)),
                ('YOM', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_type', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('vehicle_make', models.CharField(max_length=30)),
                ('vehicle_model', models.CharField(max_length=30)),
                ('passengers', models.IntegerField()),
                ('registration_number', models.CharField(max_length=30)),
                ('YOM', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
            ],
        ),
    ]
