# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-01 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialvehicle',
            old_name='phone_number3',
            new_name='phone_number',
        ),
    ]
